### ISSUE TITLE
Resolving not correct

### ISSUE THREAD

**Issue by joy-n-craft** [nacholibre/url-slicer.js#1]
"news.rufox.ru": "Inccorrect resolve: ru.ru",
    "webmailb.netzero.net": "Inccorrect resolve: net.net",
    "blogspot.com.es": "Unable to resolve domain: Query is not valid domain name.",
    "blogspot.com.br": "Unable to resolve domain: Query is not valid domain name.",
    "blogspot.co.uk": "Unable to resolve domain: Query is not valid domain name.",
    "aajtak.intoday.in": "Inccorrect resolve: in.in",
    "france3-regions.francetvinfo.fr": "Inccorrect resolve: fr.fr",
    "uk.complex.com": "Inccorrect resolve: com.com",
    "jam.canoe.ca": "Inccorrect resolve: ca.ca",
    "lifewise.canoe.ca": "Inccorrect resolve: ca.ca",
    "slam.canoe.ca": "Inccorrect resolve: ca.ca",
    "naukri.com.sjmads.com": "Inccorrect resolve: com.com",
    "en.combatarms.nexoneu.com": "Inccorrect resolve: com.com",
    "nba2kol.competgames.com": "Inccorrect resolve: com.com",

**Comment by joy-n-craft** [comment]
The issue in 

```
domain = domain.replace('.' + tld, '');
```

It should replace it from end

**Comment by joy-n-craft** [comment]
My solution

```
domain = domain.replace('.' + tld, '');
if (url.indexOf(domain) == -1) {
     domain = url.substr(0, url.length - (tld.length + 1));
}
```

A bit ugly, but works

**Comment by nacholibre** [comment]
Hello,

thank you for your feedback and sorry for the last response, in the new version this bug is fixed.
